services:
  backend:
    image: docker.io/sogoredev/gestion-de-produit:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=${DB_HOST}
      - spring.datasource.username=${DB_USERNAME}
      - spring.datasource.password=${DB_PASSWORD}
      - JAVA_TOOL_OPTIONS=-Xss200K
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: StockBackend@2024ml
      MYSQL_DATABASE: stock
      MYSQL_USER: stock
      MYSQL_PASSWORD: StockBackend@2024ml
    ports:
      - "3306:3306"
