version: '3.7'
services:
  backend:
    image: sogoredev/gestion-de-produit:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/stock
      - SPRING_DATASOURCE_USERNAME=stock
      - SPRING_DATASOURCE_PASSWORD=StockBackend@2024ml
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: StockBackend@2024ml
      MYSQL_DATABASE: stock
      MYSQL_USER: stock
      MYSQL_PASSWORD: StockBackend@2024ml
    ports:
      - "3306:3306"
