services:
  stock-back:
    image: docker.io/sogoredev/gestion-de-produit:0.0.1-SNAPSHOT
    container_name: stock-back
    restart: always
    environment:
      - spring.datasource.url=jdbc:mysql://stock-database:3306/dbStock
      - spring.datasource.username=stock
      - spring.datasource.password=StockBackend@2024ml
      - JAVA_TOOL_OPTIONS=-Xss200K
    networks:
      - applications-network

networks:
  applications-network:
    external: true
    name: applications-network
