name: Deploy Backend to VPS
on: [push]
jobs:
  deploy:
    name: create folder
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Vérifier et installer JDK 17
      - name: setup java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # Assure-toi de choisir une bonne distribution de JDK

      # Étape 2 : Checkout du code source
      - name: Checkout Code
        uses: actions/checkout@v2

      # Étape 3 : Build de l'image Docker
      - name: Build and Push Docker Image
        run: |
          ./mvnw clean package spring-boot:build-image \
          -Dspring-boot.build-image.imageName=docker.io/sogoredev/gestion-de-produit:${{github.sha}} \
          -Ddocker.publishRegistry.username=${{secrets.DOCKERHUB_USERNAME}} \
          -Ddocker.publishRegistry.password=${{secrets.DOCKERHUB_TOKEN}} \
          -Dspring-boot.build-image.publish=true

      # Étape 4 : SSH et déploiement sur VPS
      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /opt/applications/stock/backend
            docker-compose pull
            docker-compose up -d
