name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Install sshpass and rsync
        run: sudo apt-get install -y sshpass rsync

      - name: Save private key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} "echo SSH key authentication successful"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Copy JAR and docker-docker-compose.yml to VPS using rsync
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" \
            /home/runner/work/Gestion-de-stock/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/root/app

        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Run Docker Compose on VPS
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key_path: private_key.pem
          password: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /root/app/Gestion-de-stock
            docker-compose down
            docker-compose up -d --build
      - name: Cleanup private key
        run: rm private_key.pem